#%RAML 1.0
title: Kommoncare
version: 1.0.0
baseUri: http://kommoncare.com/api
types:
  ChallengeAction:
    type:
      - string
    displayName: Challenge Action
    enum:
      - lock
      - complete

/users:
  displayName: Users
  description: The collection of Kommoncare users.
  get:
    description: Get the list of users.
    responses:
      200:
        body:
          application/json:
            example: !include examples/users-get.json
  post:
    description: Create a user.
    body:
      application/json:
        example: !include examples/users-post.json
    responses:
      201:
        body:
          application/json:
            example: !include examples/users-post-response.json
  /{userId}:
    get:
/challenges:
  get:
  post:
  /{challengeId}:
    get:
    post:
      queryParameters:
        action:
          description: An identifier of a Zocial user, used to retrieve only his/her posts.
          type: string
          required: false
/categories:
  get:
    responses:
      200:
        body:
          application/json:
            example: !include examples/categories-get.json
  /{categoryId}:
    get:
      queryParameters:

/awards:
  get:
